name: Republish

#on:
#  schedule:
#    - cron: '1 18 * * *'  # Run at 6:01 pm every day.

#for now only trigger on PRs 
on:
  pull_request:

jobs:
  build-and-deploy:
    environment: github-pages
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies  
      - run: pip install -r requirements.txt
      
      #cannot use actions that require github.token as currently we cannot add it to secret 
      - name: Make the github token available for py scripts - test
        run: echo  $TOKEN
          #admin_token= python update_github_stats.py
          #printf '%s\n' "$pat_token" > github.token
        env:
           TOKEN: ${{ secrets.ADMIN_TOKEN }}
      
      - name: Regenerate Dashboard 🚀
        run: python update_dashboard.py

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
          github_token: ${{ secrets.GITHUB_TOKEN }}


