name: Republish

#on:
#  schedule:
#    - cron: '1 18 * * *'  # Run at 6:01 pm every day.

#for now only trigger on PRs 
on:
  pull_request:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies  
      - run: pip install -r requirements.txt
      
      - name: Build dashboards
        run: bash Makefile 

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
          github_token: ${{ secrets.GITHUB_TOKEN }}


